import { JetzElement } from './jetz.js';

export type ElementChild = JetzElement | HTMLElement | string | number | boolean | Function | Record<string, any> | any[] | null | undefined;
export type ElementFactory = (...args: ElementChild[]) => JetzElement;
export type AttrFactory = (value: any) => Record<string, any>;
export type EventFactory = (callback: (e: any) => void) => Record<string, (e: any) => void>;

// ---------------------------------------------------------------------------
// Query & Utility Helpers
// ---------------------------------------------------------------------------

export declare function find(selector: string): HTMLElement | null;
export declare function findAll(selector: string): NodeListOf<HTMLElement>;
export declare function text(...content: any[]): string[];

// ---------------------------------------------------------------------------
// Attribute & Style Helpers
// ---------------------------------------------------------------------------

export declare const alt: AttrFactory;
export declare const aria_: (objAria: Record<string, any>) => Record<string, any>;
export declare const base: ElementFactory;
export declare const body: ElementFactory;
export declare function css(value: any): { class: any };
export declare function css(strings: TemplateStringsArray, ...values: any[]): { class: any };
export declare const data: AttrFactory;
export declare const data_: (objData: Record<string, any>) => Record<string, any>;
export declare const height: AttrFactory;
export declare const href: AttrFactory;
export declare const id: AttrFactory;
export declare const name: AttrFactory;
export declare const placeholder: AttrFactory;
export declare const role: AttrFactory;
export declare const src: AttrFactory;
export declare const style: (styles: Record<string, any>) => { style: Record<string, any> };
export declare const tabindex: AttrFactory;
export declare const type: AttrFactory;
export declare const value: AttrFactory;
export declare const width: AttrFactory;
export declare const wrap: { wrap: string };

// ---------------------------------------------------------------------------
// HTML Elements
// ---------------------------------------------------------------------------

export declare const a: ElementFactory;
export declare const abbr: ElementFactory;
export declare const address: ElementFactory;
export declare const area: ElementFactory;
export declare const article: ElementFactory;
export declare const aside: ElementFactory;
export declare const audio: ElementFactory;
export declare const b: ElementFactory;
export declare const bdi: ElementFactory;
export declare const bdo: ElementFactory;
export declare const blockquote: ElementFactory;
export declare const br: ElementFactory;
export declare const button: ElementFactory;
export declare const canvas: ElementFactory;
export declare const caption: ElementFactory;
export declare const cite: ElementFactory;
export declare const code: ElementFactory;
export declare const col: ElementFactory;
export declare const colgroup: ElementFactory;
export declare const datalist: ElementFactory;
export declare const dd: ElementFactory;
export declare const del: ElementFactory;
export declare const details: ElementFactory;
export declare const dfn: ElementFactory;
export declare const dialog: ElementFactory;
export declare const div: ElementFactory;
export declare const dl: ElementFactory;
export declare const dt: ElementFactory;
export declare const em: ElementFactory;
export declare const embed: ElementFactory;
export declare const fieldset: ElementFactory;
export declare const figcaption: ElementFactory;
export declare const figure: ElementFactory;
export declare const footer: ElementFactory;
export declare const form: ElementFactory;
export declare const h1: ElementFactory;
export declare const h2: ElementFactory;
export declare const h3: ElementFactory;
export declare const h4: ElementFactory;
export declare const h5: ElementFactory;
export declare const h6: ElementFactory;
export declare const head: ElementFactory;
export declare const header: ElementFactory;
export declare const hgroup: ElementFactory;
export declare const hr: ElementFactory;
export declare const htmlElement: ElementFactory;
export declare const i: ElementFactory;
export declare const iframe: ElementFactory;
export declare const img: ElementFactory;
export declare const input: ElementFactory;
export declare const inputButton: ElementFactory;
export declare const inputCheckbox: ElementFactory;
export declare const inputColor: ElementFactory;
export declare const inputDate: ElementFactory;
export declare const inputDateTimeLocal: ElementFactory;
export declare const inputEmail: ElementFactory;
export declare const inputFile: ElementFactory;
export declare const inputHidden: ElementFactory;
export declare const inputImage: ElementFactory;
export declare const inputMonth: ElementFactory;
export declare const inputNumber: ElementFactory;
export declare const inputPassword: ElementFactory;
export declare const inputRadio: ElementFactory;
export declare const inputRange: ElementFactory;
export declare const inputReset: ElementFactory;
export declare const inputSearch: ElementFactory;
export declare const inputSubmit: ElementFactory;
export declare const inputTel: ElementFactory;
export declare const inputText: ElementFactory;
export declare const inputTime: ElementFactory;
export declare const inputUrl: ElementFactory;
export declare const inputWeek: ElementFactory;
export declare const ins: ElementFactory;
export declare const kbd: ElementFactory;
export declare const label: ElementFactory;
export declare const legend: ElementFactory;
export declare const li: ElementFactory;
export declare const link: ElementFactory;
export declare const main: ElementFactory;
export declare const map: ElementFactory;
export declare const mark: ElementFactory;
export declare const menu: ElementFactory;
export declare const meta: ElementFactory;
export declare const meter: ElementFactory;
export declare const nav: ElementFactory;
export declare const noscript: ElementFactory;
export declare const object: ElementFactory;
export declare const ol: ElementFactory;
export declare const optgroup: ElementFactory;
export declare const option: ElementFactory;
export declare const output: ElementFactory;
export declare const p: ElementFactory;
export declare const param: ElementFactory;
export declare const picture: ElementFactory;
export declare const pre: ElementFactory;
export declare const progress: ElementFactory;
export declare const q: ElementFactory;
export declare const rp: ElementFactory;
export declare const rt: ElementFactory;
export declare const ruby: ElementFactory;
export declare const s: ElementFactory;
export declare const samp: ElementFactory;
export declare const search: ElementFactory;
export declare const script: ElementFactory;
export declare const section: ElementFactory;
export declare const select: ElementFactory;
export declare const small: ElementFactory;
export declare const slot: ElementFactory;
export declare const source: ElementFactory;
export declare const span: ElementFactory;
export declare const strong: ElementFactory;
export declare const styleElement: ElementFactory;
export declare const sub: ElementFactory;
export declare const summary: ElementFactory;
export declare const sup: ElementFactory;
export declare const table: ElementFactory;
export declare const tbody: ElementFactory;
export declare const td: ElementFactory;
export declare const template: ElementFactory;
export declare const textarea: ElementFactory;
export declare const tfoot: ElementFactory;
export declare const th: ElementFactory;
export declare const thead: ElementFactory;
export declare const time: ElementFactory;
export declare const title: ElementFactory;
export declare const tr: ElementFactory;
export declare const track: ElementFactory;
export declare const u: ElementFactory;
export declare const ul: ElementFactory;
export declare const video: ElementFactory;
export declare const wbr: ElementFactory;

// ---------------------------------------------------------------------------
// Event Listeners
// ---------------------------------------------------------------------------

export declare const onAbort: EventFactory;
export declare const onAnimationEnd: EventFactory;
export declare const onAnimationIteration: EventFactory;
export declare const onAnimationstart: EventFactory;
export declare const onAuxclick: EventFactory;
export declare const onBeforecopy: EventFactory;
export declare const onBeforecut: EventFactory;
export declare const onBeforeinput: EventFactory;
export declare const onBeforematch: EventFactory;
export declare const onBeforepaste: EventFactory;
export declare const onBeforexrselect: EventFactory;
export declare const onBlur: EventFactory;
export declare const onCancel: EventFactory;
export declare const onCanplay: EventFactory;
export declare const onCanplaythrough: EventFactory;
export declare const onChange: EventFactory;
export declare const onClick: EventFactory;
export declare const onClose: EventFactory;
export declare const onContentvisibilityautostatechange: EventFactory;
export declare const onContextlost: EventFactory;
export declare const onContextmenu: EventFactory;
export declare const onContextrestored: EventFactory;
export declare const onCopy: EventFactory;
export declare const onCuechange: EventFactory;
export declare const onCut: EventFactory;
export declare const onDblclick: EventFactory;
export declare const onDrag: EventFactory;
export declare const onDragend: EventFactory;
export declare const onDragenter: EventFactory;
export declare const onDragleave: EventFactory;
export declare const onDragover: EventFactory;
export declare const onDragstart: EventFactory;
export declare const onDrop: EventFactory;
export declare const onDurationchange: EventFactory;
export declare const onEmptied: EventFactory;
export declare const onEnded: EventFactory;
export declare const onError: EventFactory;
export declare const onFocus: EventFactory;
export declare const onFormdata: EventFactory;
export declare const onFullscreenchange: EventFactory;
export declare const onFullscreenerror: EventFactory;
export declare const onGotpointercapture: EventFactory;
export declare const onInput: EventFactory;
export declare const onInvalid: EventFactory;
export declare const onKeydown: EventFactory;
export declare const onKeypress: EventFactory;
export declare const onKeyup: EventFactory;
export declare const onLoad: EventFactory;
export declare const onLoadeddata: EventFactory;
export declare const onLoadedmetadata: EventFactory;
export declare const onLoadstart: EventFactory;
export declare const onLostpointercapture: EventFactory;
export declare const onMousedown: EventFactory;
export declare const onMouseenter: EventFactory;
export declare const onMouseleave: EventFactory;
export declare const onMousemove: EventFactory;
export declare const onMouseout: EventFactory;
export declare const onMouseover: EventFactory;
export declare const onMouseup: EventFactory;
export declare const onMousewheel: EventFactory;
export declare const onPaste: EventFactory;
export declare const onPause: EventFactory;
export declare const onPlay: EventFactory;
export declare const onPlaying: EventFactory;
export declare const onPointercancel: EventFactory;
export declare const onPointerdown: EventFactory;
export declare const onPointerenter: EventFactory;
export declare const onPointerleave: EventFactory;
export declare const onPointermove: EventFactory;
export declare const onPointerout: EventFactory;
export declare const onPointerover: EventFactory;
export declare const onPointerrawupdate: EventFactory;
export declare const onPointerup: EventFactory;
export declare const onProgress: EventFactory;
export declare const onRatechange: EventFactory;
export declare const onReset: EventFactory;
export declare const onResize: EventFactory;
export declare const onScroll: EventFactory;
export declare const onSearch: EventFactory;
export declare const onSecuritypolicyviolation: EventFactory;
export declare const onSeeked: EventFactory;
export declare const onSeeking: EventFactory;
export declare const onSelect: EventFactory;
export declare const onSelectionchange: EventFactory;
export declare const onSelectstart: EventFactory;
export declare const onSlotchange: EventFactory;
export declare const onStalled: EventFactory;
export declare const onSubmit: EventFactory;
export declare const onSuspend: EventFactory;
export declare const onTimeupdate: EventFactory;
export declare const onToggle: EventFactory;
export declare const onTransitioncancel: EventFactory;
export declare const onTransitionend: EventFactory;
export declare const onTransitionrun: EventFactory;
export declare const onTransitionstart: EventFactory;
export declare const onVolumechange: EventFactory;
export declare const onWaiting: EventFactory;
export declare const onWebkitanimationend: EventFactory;
export declare const onWebkitanimationiteration: EventFactory;
export declare const onWebkitanimationstart: EventFactory;
export declare const onWebkitfullscreenchange: EventFactory;
export declare const onWebkitfullscreenerror: EventFactory;
export declare const onWebkittransitionend: EventFactory;
export declare const onWheel: EventFactory;
