/**
 * Smoke test for the features documented in README.md (core `jetz.js` API).
 * Bundled with rspack and executed in a real browser: `pnpm test:smoke`.
 */
import {
	Component, Dispatcher, Jetz, JetzElement, Raw, State,
	_else, _elseif, _if, _show, addScript, createElement, createList, flatMap,
	html, ifElse, listen, listOf, loop, onCreate, onDestroy, onMount, onUpdate,
	range, rememberOf, sequenceOf, stateOf
} from '../../src/lib/jetz.js';
import {
	a, aria_, button, css, data_, div, find, findAll, href, id, img, inputText,
	label, li, main, nav, p, placeholder, span, src, style, strong, text, ul
} from '../../src/lib/jetz-ui.js';
import { route, Router, link } from '../../src/lib/jetz-router.js';
import { Landing } from '../../src/components/landing/landing.js';
import { counter as counterPage } from '../../src/components/counter/counter.js';

// ---------------------------------------------------------------------------
// tiny harness - the suite runs twice (phase 1 + one reload for rememberOf),
// so the results of both page loads are accumulated in sessionStorage
// ---------------------------------------------------------------------------
const KEY_RESULTS = 'jetz-smoke-results';
const KEY_PHASE = 'jetz-smoke-phase';
const previousResults = sessionStorage.getItem(KEY_RESULTS) ?? '';
const isReloadPhase = sessionStorage.getItem(KEY_PHASE) === 'reload';
if (!isReloadPhase) sessionStorage.setItem(KEY_PHASE, 'reload');

const results = [];
let currentSection = '';

function section(name) {
	currentSection = name;
	results.push(`# ${name}`);
}

/** Safe one line description of a value for the report (element trees are circular). */
function describe(value) {
	if (value === null) return 'null';
	if (value instanceof JetzElement) return `JetzElement<${value.tagName}>`;
	if (value instanceof State) return `State(${value.getValue()})`;
	if (typeof Node !== 'undefined' && value instanceof Node) return `<${value.nodeName.toLowerCase()}>`;
	if (typeof value === 'function') return `[function ${value.name || 'anonymous'}]`;
	let text;
	try {
		text = JSON.stringify(value) ?? String(value);
	} catch (error) {
		text = String(value);
	}
	text = text.replace(/\s+/g, ' ');
	return text.length > 110 ? `${text.slice(0, 107)}...` : text;
}

function assert(label, actual, expected) {
	const ok = actual === expected;
	results.push(`${ok ? 'PASS' : 'FAIL'} :: ${currentSection} :: ${label} | actual: ${describe(actual)} | expected: ${describe(expected)}`);
}

/** README style comparison (`count.value == 1`), where a state coerces to its value. */
function assertLoose(label, actual, expected) {
	const ok = actual == expected;
	results.push(`${ok ? 'PASS' : 'FAIL'} :: ${currentSection} :: ${label} (loose) | actual: ${describe(String(actual))} | expected: ${describe(String(expected))}`);
}

function finish() {
	const pre = document.createElement('pre');
	pre.id = 'results';
	pre.textContent = [previousResults, results.join('\n')].filter(Boolean).join('\n');
	document.body.appendChild(pre);
	window.__SMOKE_DONE__ = true;
}

const textOf = selector => find(selector).textContent;
const itemsOf = selector => Array.from(findAll(selector)).map(element => element.textContent);

/** Renders a tree into its own container so the sections stay independent. */
function mountInto(name, tree, event) {
	const container = document.createElement('div');
	container.id = `section-${name}`;
	document.body.appendChild(container);
	Jetz.mount(tree, container, event);
	return container;
}

// Created first - and in the same order on both page loads - so the remembered
// ids (generated by creation order) stay stable across the reload.
const rememberedNumber = rememberOf(0);
const rememberedList = rememberOf([]);
const keyedRememberedList = rememberOf('smoke.keyed-list', []);
// gap fix: listOf(...).asRemember() must persist like rememberOf([]) does
const lateRememberedList = listOf('seed').asRemember();

// ---------------------------------------------------------------------------
// phase 2 (after the reload): remembered values must be restored
// ---------------------------------------------------------------------------
function runReloadPhase() {
	section('rememberOf (after page reload)');
	assert('remembered number restored from localStorage', rememberedNumber.getValue(), 42);
	assert('remembered list restored from localStorage', rememberedList.size, 1);
	assert('remembered list keeps its item', String(rememberedList.first()), 'persisted');
	assert('keyed remembered list restores after reload', keyedRememberedList.first(), 'keyed-persisted');
	assert('values are persisted in localStorage', typeof localStorage.getItem('app-remember-state'), 'string');
	// gap fix: asRemember() persistence across reloads
	assert('asRemember() list restored from localStorage', JSON.stringify(lateRememberedList.values), '["from-phase-1","also-pushed"]');
	assert('asRemember() list stays remembered after reload', lateRememberedList.isRemember, true);
	sessionStorage.removeItem(KEY_PHASE);
	sessionStorage.removeItem(KEY_RESULTS);
	finish();
}

// ---------------------------------------------------------------------------
// phase 1: the whole documented API
// ---------------------------------------------------------------------------
function runMainSuite() {
	// install surface: the published package entry points must stay importable
	// from the app source tree (root src/lib/* are thin re-export shims)
	section('package entry points');

	assert('jetz core entry exposes Jetz', typeof Jetz, 'function');
	assert('jetz core entry exposes stateOf', typeof stateOf, 'function');
	assert('jetz ui entry exposes div', typeof div, 'function');
	assert('jetz ui entry exposes find', typeof find, 'function');
	assert('published package root resolves', typeof Jetz.version, 'string');

	// README: "How to Render Elements" / "Thinking in Jetz"
	section('render: elements, nesting and arrays');

	let mountStarted = false;
	let mountLoaded = false;

	const App = () => main(
		div({ id: 'hello' }, 'Hello World'),
		ul(css`todo-list`,
			[1, 2, 3].map(number => li(css`todo-item`, 'Item ' + number))
		),
		div({ id: 'label-box' },
			label(id('my-label'), 'You are not yet clicked'),
			button({ id: 'plain-click', onclick() { find('#my-label').innerText = 'Clicked via innerText'; } }, 'Click me'),
			button({ id: 'jetz-click', onclick() { find('#my-label').$.text('Clicked via $'); } }, 'Click me ($)')
		)
	);

	Jetz.mount(App, find('#app'), {
		onStart() { mountStarted = true; },
		onLoad() { mountLoaded = true; }
	});

	assert('element renders into the mount target', textOf('#hello'), 'Hello World');
	assert('nesting, array children and the css helper', findAll('.todo-item').length, 3);
	assert('NodeList.last() prototype helper', findAll('.todo-item').last().textContent, 'Item 3');
	assert('css helper sets the tag', find('.todo-list').tagName, 'UL');
	assert('mount option onStart is called', mountStarted, true);
	assert('mount option onLoad is called', mountLoaded, true);

	find('#plain-click').click();
	assert('find(selector) returns the DOM element', textOf('#my-label'), 'Clicked via innerText');
	find('#jetz-click').click();
	assert('$.text() back reference to the JetzElement', textOf('#my-label'), 'Clicked via $');

	// README: attribute helpers
	section('attribute helpers');

	const attrBox = div({ id: 'attr-box' },
		inputText(id('name-input'), placeholder('Input your name...')),
		a(href('https://example.com'), 'link'),
		img(src('data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'), { alt: 'logo' }),
		span(data_({ role: 'demo' }), aria_({ label: 'demo label' }), 'prefixed'),
		div(css`styled`, style({ color: 'rgb(255, 0, 0)' }), 'styled'),
		div(text`Hello ${'World'}!`)
	);
	mountInto('attributes', attrBox);

	assert('id() helper', find('#name-input').tagName, 'INPUT');
	assert('placeholder() helper', find('#name-input').getAttribute('placeholder'), 'Input your name...');
	assert('href() helper', find('#attr-box a').getAttribute('href'), 'https://example.com');
	assert('plain attribute object', find('#attr-box img').getAttribute('alt'), 'logo');
	assert('data_() prefix helper', find('#attr-box span').dataset.role, 'demo');
	assert('aria_() prefix helper', find('#attr-box span').getAttribute('aria-label'), 'demo label');
	assert('style attribute helper', find('#attr-box .styled').style.color, 'rgb(255, 0, 0)');
	assert('text tagged template', find('#attr-box div:last-child').textContent, 'Hello World!');

	// README: "Event Listener" / "DOM Element"
	section('event listeners');

	let plainCount = 0;
	let boundThis = null;
	let methodCount = 0;
	const methodHandler = () => { methodCount++; };
	const eventCounter = stateOf(0);

	const methodButton = button({ id: 'ev-method' }, 'method');
	mountInto('events', div(
		button({ id: 'ev-plain', onclick() { plainCount++; } }, 'plain'),
		button({ id: 'ev-this', onclick() { boundThis = this; } }, 'this'),
		button({ id: 'ev-state', onclick() { eventCounter.value++; } }, 'state'),
		methodButton,
		p({ id: 'ev-out' }, 'Count : ', eventCounter)
	));

	find('#ev-plain').click();
	assert('onclick attribute listener runs', plainCount, 1);
	find('#ev-this').click();
	assert('onclick listener `this` is the JetzElement', boundThis instanceof JetzElement, true);
	assert('`this` is the instance stored on the DOM element', boundThis, find('#ev-this').$);
	assert('`this` gives access to the DOM node', boundThis.o, find('#ev-this'));
	find('#ev-state').click();
	assert('state bound child updates on click', textOf('#ev-out'), 'Count : 1');

	methodButton.on('click', methodHandler);
	find('#ev-method').click();
	assert('on() attaches a listener after render', methodCount, 1);
	methodButton.off('click', methodHandler);
	find('#ev-method').click();
	assert('off() detaches the listener again', methodCount, 1);

	const lateOn = div({ id: 'late-on' }, 'late');
	mountInto('late-listener', lateOn);
	let lateClicks = 0;
	lateOn.on('click', () => { lateClicks++; });
	find('#late-on').click();
	assert('on() attaches to an already rendered element', lateClicks, 1);
	const chainProbe = div('chain');
	assert('on() is chainable', chainProbe.on('click', () => { }) === chainProbe, true);

	// README: "Component or Function or Variable" / "Passing Data between Function or Component"
	section('components');

	let helloMessage = '';
	let badgeRendered = false;

	class MyButton extends Component {
		say = '';
		word = '';
		constructor(say, word) {
			super();
			this.say = say;
			this.word = word;
		}
		showMessage() {
			helloMessage = `${this.say} ${this.word}`;
			find('#component-msg').textContent = helloMessage;
		}
		render() {
			return button(css`btn`, 'Show Message', {
				onclick: () => this.showMessage()
			});
		}
	}

	class Badge extends Component {
		onRendered() { badgeRendered = true; }
		render() { return span(css`badge`, 'badge'); }
	}

	const PostCard = (title, content) => div(css`card`,
		div(css`card-title`, title),
		div(css`card-body`, p(content))
	);
	const userPosts = [
		{ title: 'Black Bird', message: 'A bird with black color' },
		{ title: 'Red Bird', message: 'A bird with red color' },
		{ title: 'Green Bird', message: 'A bird with green color' }
	];

	mountInto('components', main(
		div({ id: 'component-msg' }),
		new MyButton('Hello', 'World'),
		MyButton.new('Hola', 'Mundo'),
		new Badge(),
		div(css`container`,
			div(css`row`,
				div(css`col-12`,
					loop(userPosts, post => PostCard(post.title, post.message))
				)
			)
		)
	));

	assert('component class renders its element', findAll('#section-components button.btn').length, 2);
	assert('component content', findAll('#section-components button.btn')[0].textContent, 'Show Message');
	findAll('#section-components button.btn')[0].click();
	assert('component with data passed to `new`', helloMessage, 'Hello World');
	assert('component side effect reached the page', textOf('#component-msg'), 'Hello World');
	findAll('#section-components button.btn')[1].click();
	assert('Component.new() static factory', helloMessage, 'Hola Mundo');
	assert('Component onRendered lifecycle hook', badgeRendered, true);
	assert('function component rendered through loop()', findAll('#section-components .card').length, 3);
	assert('function component with passed data', textOf('#section-components .card-title'), 'Black Bird');
	assert('function component body', textOf('#section-components .card .card-body p'), 'A bird with black color');

	// README: "State Management" / "stateOf"
	section('stateOf');

	let subscriberCalls = 0;
	let lastPair = '';
	const counter = stateOf(0);
	const nameState = stateOf('');
	const user = stateOf({ name: 'Ada', age: 36 });
	const boundInput = inputText(id('bind-input'), { bind: nameState, placeholder: 'Input your name...' });

	mountInto('state', div(
		{ id: 'state-box' },
		button({ id: 'state-count', onclick() { counter.value++; } }, 'Count : ', counter),
		div({ id: 'name-out' }, 'My name is : ', nameState),
		boundInput,
		div({ id: 'nested-state' }, 'age: ', user.age)
	));

	const listener = (newValue, oldValue) => {
		subscriberCalls++;
		lastPair = `${oldValue}->${newValue}`;
	};
	counter.subscribe(listener);

	find('#state-count').click();
	assert('state bound as a child follows .value writes', textOf('#state-count'), 'Count : 1');
	assert('getValue() reads the value', counter.getValue(), 1);
	assertLoose('README style read (.value == n)', counter.value == 1, true);
	assert('subscribe listener receives (newValue, oldValue)', lastPair, '0->1');

	counter.setState(5);
	assert('setState() writes the value', counter.getValue(), 5);
	find('#state-count').click();
	assert('README style write (.value++)', counter.getValue(), 6);
	counter.setState(7);
	assert('subscribe called on every change', subscriberCalls, 4);
	assert('subscribe received the last change', lastPair, '6->7');
	counter.unsubscribe(listener);
	counter.setState(8);
	assert('unsubscribe() stops the listener', subscriberCalls, 4);

	const bindInputEl = find('#bind-input');
	bindInputEl.value = 'Jetz';
	bindInputEl.dispatchEvent(new Event('input', { bubbles: true }));
	assert('bind: input value is written to the state', nameState.getValue(), 'Jetz');
	assert('bind: bound text node follows the state', textOf('#name-out'), 'My name is : Jetz');
	nameState.value = 'From state';
	assert('bind: state value is written back to the input', bindInputEl.value, 'From state');

	user.age.value = 37;
	assert('object state: nested property is a state', textOf('#nested-state'), 'age: 37');
	assertLoose('object state: nested value read', user.age == 37, true);

	// README: Dispatcher + a state holding an element
	section('Dispatcher and element state');

	let lastAction = '';
	const pageContent = stateOf(div('Home page'));
	const dispatcher = new Dispatcher((action, page) => {
		lastAction = `${action}:${page}`;
		if (action === 'home') pageContent.value = div('Home page');
		else if (action === 'about') pageContent.value = div('About page');
		else if (action === 'contact-us') pageContent.value = div('Contact page');
	});

	mountInto('dispatcher', main(
		nav(ul(
			li('Home').on('click', () => dispatcher.dispatch('home', 1)),
			li('About').on('click', () => dispatcher.dispatch('about', 2)),
			li('Contact Us').on('click', () => dispatcher.dispatch('contact-us', 3))
		)),
		div({ id: 'page-content' }, pageContent)
	));

	assert('element state renders its element', textOf('#page-content'), 'Home page');
	find('#section-dispatcher nav li:nth-child(2)').click();
	assert('dispatch() swaps the element state value', textOf('#page-content'), 'About page');
	assert('dispatch() forwards extra arguments', lastAction, 'about:2');
	find('#section-dispatcher nav li:nth-child(3)').click();
	assert('element state replaces the rendered element', textOf('#page-content'), 'Contact page');

	// README: "listOf" / "ListState API" / "Example State"
	section('listOf / ListState API');

	const todos = listOf('first', 'second');
	mountInto('list', div(
		ul({ id: 'todo-ul' }, loop(todos, item => li(css`todo`, item))),
		button({ id: 'add-todo', onclick: () => todos.push(`New Item ${todos.length + 1}`) }, 'Add new item')
	));

	assert('listOf renders its items', itemsOf('#todo-ul .todo').join(','), 'first,second');
	find('#add-todo').click();
	assert('push() adds an item and re-renders', itemsOf('#todo-ul .todo').length, 3);
	assert('pushed item shows its value', itemsOf('#todo-ul .todo').pop(), 'New Item 3');

	todos.set(['alpha', 'beta']);
	assert('set() replaces all items', itemsOf('#todo-ul .todo').join(','), 'alpha,beta');
	const mappedTodos = todos.map(item => item.toUpperCase());
	assert('map() returns transformed values', mappedTodos.join(','), 'ALPHA,BETA');
	assert('map() leaves the list unchanged', itemsOf('#todo-ul .todo').join(','), 'alpha,beta');
	todos.transform(item => item.toUpperCase());
	assert('transform() updates the items', itemsOf('#todo-ul .todo').join(','), 'ALPHA,BETA');
	todos.insertAt(0, 'inserted');
	assert('insertAt() inserts at the position', itemsOf('#todo-ul .todo').join(','), 'inserted,ALPHA,BETA');
	todos.sort();
	assert('sort() re-renders in order', itemsOf('#todo-ul .todo').join(','), 'ALPHA,BETA,inserted');
	todos.remove(todos.values[1]);
	assert('remove() removes by value', itemsOf('#todo-ul .todo').join(','), 'ALPHA,inserted');
	todos.remove('not-present');
	assert('remove() is safe for a missing item', todos.size, 2);
	todos.removeAt(0);
	assert('removeAt() removes by index', itemsOf('#todo-ul .todo').join(','), 'inserted');
	assert('size', todos.size, 1);
	assert('first()', String(todos.first()), 'inserted');
	assert('last()', String(todos.last()), 'inserted');
	assert('at()', String(todos.at(0)), 'inserted');
	assert('indexOf()', todos.indexOf('inserted'), 0);
	assert('includes()', todos.includes('inserted'), true);
	assert('filter() returns a plain array', JSON.stringify(todos.filter(() => true)), '["inserted"]');
	assert('take() returns the leading items', JSON.stringify(todos.take(1)), '["inserted"]');
	assert('values exposes the item array', JSON.stringify(todos.values), '["inserted"]');
	todos.clear();
	assert('clear() empties the list', todos.size, 0);
	assert('clear() removes the rendered items', itemsOf('#todo-ul .todo').length, 0);

	// README: "sequenceOf"
	section('sequenceOf (unique string/number values)');

	const sequence = sequenceOf('a', 'b');
	mountInto('sequence', div(
		ul({ id: 'sequence-ul' },
			loop(sequence, item => li(css`seq`, item, button('delete', { onclick() { sequence.remove(item); } })))
		),
		button({ id: 'add-seq', onclick: () => sequence.push('a') }, 'Add duplicate')
	));

	assert('sequenceOf renders its items', findAll('#sequence-ul .seq').length, 2);
	find('#add-seq').click();
	assert('a duplicate value becomes a separate item', findAll('#sequence-ul .seq').length, 3);
	assert('duplicate values are distinct objects', sequence.values[0] !== sequence.values[2], true);
	assertLoose('duplicate values stay equal by value', String(sequence.values[0]) == String(sequence.values[2]), true);
	findAll('#sequence-ul .seq button')[2].click();
	assert('remove() with the iterated value removes one item', findAll('#sequence-ul .seq').length, 2);

	// README: "Conditional Element"
	section('conditional elements (_if / _elseif / _else)');

	const branchCounter = stateOf(0);
	mountInto('conditional', div(
		div('Number is : ',
			div(_if(() => branchCounter.value == 0), 'Zero'),
			div(_elseif(() => branchCounter.value == 1), 'One'),
			div(_elseif(() => branchCounter.value == 2), 'Two'),
			div(_else, 'More (', branchCounter, ')')
		).id('branch-box'),
		div(
			div(_if(() => 1 > 3), 'content'),
			'placed after'
		).id('never-box'),
		button({ id: 'branch-count', onclick() { branchCounter.value++; } }, 'Count')
	));

	assert('_if shows the matching branch', textOf('#branch-box'), 'Number is : Zero');
	find('#branch-count').click();
	assert('_elseif for value 1', textOf('#branch-box'), 'Number is : One');
	find('#branch-count').click();
	assert('_elseif for value 2', textOf('#branch-box'), 'Number is : Two');
	find('#branch-count').click();
	assert('_else fallback branch', textOf('#branch-box'), 'Number is : More (3)');
	branchCounter.value = 0;
	assert('_if is shown again after the state changes back', textOf('#branch-box'), 'Number is : Zero');
	assert('a false _if hides its element', textOf('#never-box'), 'placed after');

	// README: _else example - the _if element is the first child of its parent
	section('conditional elements (_else)');

	const isShow = stateOf(true);
	mountInto('else-branch', div(
		div(
			div(_if(() => isShow.value), 'Im true'),
			div(_else, 'Im false')
		).id('show-box'),
		button({ id: 'toggle-show', onclick() { isShow.value = !isShow.value; } }, 'Change value')
	));

	assert('_else: truthy branch is rendered first', textOf('#show-box'), 'Im true');
	find('#toggle-show').click();
	assert('_else: falsy branch appears (the _if element was the first child)', textOf('#show-box'), 'Im false');
	find('#toggle-show').click();
	assert('_else: truthy branch is restored', textOf('#show-box'), 'Im true');

	// conditional groups must resolve their branch on the very first render too
	section('conditional elements on first render');

	mountInto('elseif-first-render', div(
		div(
			div(_if(() => false), 'if branch'),
			div(_elseif(() => true), 'elseif branch')
		).id('elseif-first-box')
	));
	assert('_elseif branch shows on the first render', textOf('#elseif-first-box'), 'elseif branch');

	mountInto('else-first-render', div(
		div(
			div(_if(() => false), 'if branch'),
			div(_else, 'else branch')
		).id('else-first-box')
	));
	assert('_else branch shows on the first render', textOf('#else-first-box'), 'else branch');

	// README: "_show is an alias of _if"
	section('_show alias');

	mountInto('show-alias', div({ id: 'show-alias-box' },
		div(_show(() => true), 'always'),
		div(_show(() => false), 'never')
	));
	assert('_show is an alias of _if', textOf('#show-alias-box'), 'always');

	// README: "Inline conditional with ifElse"
	section('ifElse');

	const ifElseState = stateOf(true);
	const ifElseCounter = stateOf(0);
	mountInto('if-else', div(
		div({ id: 'ifelse-host' },
			span('before|'),
			ifElse(() => ifElseState.value, () => div('Im true'), () => 'Im false'),
			span('|after')
		),
		div({ id: 'ifelse-nested' },
			ifElse(() => ifElseCounter.value === 0, () => div('Zero'), () => div('Non-zero: ', ifElseCounter))
		),
		div({ id: 'ifelse-array' }, ifElse(() => true, () => [div('a'), 'b'])),
		div({ id: 'ifelse-noelse' }, ifElse(() => false, () => 'never'))
	));

	assert('ifElse renders the truthy branch', textOf('#ifelse-host'), 'before|Im true|after');
	assert('ifElse adds no wrapper around the branch', findAll('#ifelse-host > *').length, 3);
	ifElseState.value = false;
	assert('ifElse swaps to the falsy branch', textOf('#ifelse-host'), 'before|Im false|after');
	ifElseState.value = true;
	assert('ifElse swaps back to the truthy branch', textOf('#ifelse-host'), 'before|Im true|after');
	assert('ifElse nested condition (truthy)', textOf('#ifelse-nested'), 'Zero');
	ifElseCounter.value = 5;
	assert('ifElse nested condition (falsy)', textOf('#ifelse-nested'), 'Non-zero: 5');
	ifElseCounter.value = 0;
	assert('ifElse nested branch restored', textOf('#ifelse-nested'), 'Zero');
	assert('ifElse flattens array branch results', textOf('#ifelse-array'), 'ab');
	assert('ifElse without a falsy callback renders nothing', textOf('#ifelse-noelse'), '');

	// README: "Element Utilities"
	section('element utilities');

	let startCalled = false;
	let renderedCalled = false;
	const utilitiesChild = inputText({ id: 'utils-focus' });
	const attrsDiv = div({ id: 'utils-attrs', 'data-id': 'x' }, 'attrs');
	const valueInput = inputText({ id: 'utils-input' });
	const classBox = div({ id: 'utils-classes' }, 'classes');
	const utilitiesBox = div({ id: 'utils-box' }, utilitiesChild, attrsDiv, valueInput, classBox);
	utilitiesBox.onStart(() => { startCalled = true; });
	utilitiesBox.onRendered(() => { renderedCalled = true; });
	mountInto('utilities', utilitiesBox);

	assert('onStart() runs before render', startCalled, true);
	assert('onRendered() runs after mount', renderedCalled, true);
	assert('attr() reads a pending/rendered attribute', utilitiesBox.attr('id'), 'utils-box');
	assert('data() reads a data-* attribute', attrsDiv.data('id'), 'x');
	valueInput.value('set by helper');
	assert('value() writes the input value', find('#utils-input').value, 'set by helper');
	assert('value() reads the input value', valueInput.value(), 'set by helper');

	utilitiesBox.setStyle({ color: 'rgb(0, 0, 255)' });
	assert('setStyle() applies styles after render', find('#utils-box').style.color, 'rgb(0, 0, 255)');
	assert('getStyle() reads a style value', utilitiesBox.getStyle('color'), 'rgb(0, 0, 255)');
	utilitiesBox.disable();
	assert('disable() sets the disabled attribute', utilitiesBox.attr('disabled'), 'disabled');
	utilitiesBox.enable();
	assert('enable() removes the disabled attribute', utilitiesBox.attr('disabled'), null);

	utilitiesChild.focus();
	assert('focus() focuses the element', document.activeElement === find('#utils-focus'), true);
	utilitiesChild.blur();
	assert('blur() releases the focus', document.activeElement === document.body, true);
	assert('getParent() returns the parent JetzElement', utilitiesChild.getParent() === utilitiesBox, true);

	classBox.addClass('active');
	assert('addClass() adds a class', find('#utils-classes').className, 'active');
	classBox.addClass('one two');
	assert('addClass() accepts several classes', find('#utils-classes').className, 'active one two');
	classBox.replaceClass('one', 'three');
	assert('replaceClass() replaces a class', find('#utils-classes').className, 'active three two');
	classBox.toggleClass('active');
	assert('toggleClass() removes an existing class', find('#utils-classes').className, 'three two');
	classBox.removeClass('three');
	assert('removeClass() removes a class', find('#utils-classes').className, 'two');
	classBox.removeClass('*');
	assert('removeClass("*") clears every class', find('#utils-classes').getAttribute('class'), null);
	classBox.addAttr('title', 'hi');
	assert('addAttr() sets an attribute', classBox.attr('title'), 'hi');
	classBox.removeAttr('title');
	assert('removeAttr() removes an attribute', classBox.attr('title'), null);

	// the utilities work before render too
	const detachedBox = div({ id: 'detached' }, 'detached');
	assert('attr() reads a pending attribute', detachedBox.attr('id'), 'detached');
	detachedBox.setStyle({ color: 'rgb(1, 2, 3)' });
	assert('getStyle() reads a pending style', detachedBox.getStyle('color'), 'rgb(1, 2, 3)');
	mountInto('detached', detachedBox);
	assert('pending attributes are applied on render', find('#detached').getAttribute('id'), 'detached');
	assert('pending styles are applied on render', find('#detached').style.color, 'rgb(1, 2, 3)');

	const idBox = div('id helper').id('late-id');
	mountInto('id-helper', idBox);
	assert('id() sets the id before render', textOf('#late-id'), 'id helper');
	assert('findId() resolves the element by id', idBox.findId('late-id') === idBox, true);

	const textBox = div({ id: 'utils-text' }, 'before');
	mountInto('utils-text', textBox);
	textBox.text('after');
	assert('text() replaces the inner text', textOf('#utils-text'), 'after');

	const emptyBox = div({ id: 'empty-me' }, 'a', 'b');
	mountInto('empty', emptyBox);
	emptyBox.empty();
	assert('empty() clears the children', find('#empty-me').innerHTML, '');
	const removeBox = div({ id: 'remove-me' }, 'bye');
	mountInto('remove', removeBox);
	removeBox.remove();
	assert('remove() detaches the element', find('#remove-me'), null);

	// README: "Utilities"
	section('utilities (html, collection helpers, exports)');

	mountInto('utilities-raw', div({ id: 'raw-box' }, html(`<strong class="raw-strong">raw html</strong>`)));
	assert('html() renders real DOM nodes', textOf('#raw-box strong.raw-strong'), 'raw html');
	assert('range()', JSON.stringify(range(1, 3)), '[1,2,3]');
	assert('flatMap()', JSON.stringify(flatMap([1, [2, [3]], 4])), '[1,2,3,4]');
	assert('createList()', JSON.stringify(createList(3, index => `Item ${index}`)), '["Item 0","Item 1","Item 2"]');
	assert('Array.prototype.last()', [1, 2, 3].last(), 3);
	assert('Array.prototype.take()', JSON.stringify([1, 2, 3].take(2)), '[1,2]');
	assert('Number.prototype.range()', JSON.stringify((3).range(5)), '[3,4,5]');
	assert('html() returns a Raw instance', html('x') instanceof Raw, true);
	assert('createElement() returns a JetzElement', createElement('section', {}, 'x') instanceof JetzElement, true);
	mountInto('create-element', createElement('section', { id: 'made-by-create-element' }, 'custom'));
	assert('createElement() result renders', textOf('#made-by-create-element'), 'custom');

	// README: framework level helpers
	section('framework helpers');

	assert('Jetz.version', Jetz.version, '1.1.1');
	const styleCount = document.head.querySelectorAll('style').length;
	Jetz.style('body { margin: 0 }');
	assert('Jetz.style() injects a style tag', document.head.querySelectorAll('style').length, styleCount + 1);
	const unmountTarget = document.createElement('div');
	document.body.appendChild(unmountTarget);
	Jetz.mount(div('to be cleared'), unmountTarget);
	assert('Jetz.mount() renders into a plain container', unmountTarget.textContent, 'to be cleared');
	Jetz.unmount(unmountTarget);
	assert('Jetz.unmount() clears the container', unmountTarget.innerHTML, '');
	const selectorTarget = document.createElement('div');
	selectorTarget.id = 'unmount-by-selector';
	document.body.appendChild(selectorTarget);
	Jetz.mount(div('selector target'), '#unmount-by-selector');
	assert('Jetz.mount() accepts a selector string', selectorTarget.textContent, 'selector target');
	Jetz.unmount('#unmount-by-selector');
	assert('Jetz.unmount() accepts a selector string', selectorTarget.innerHTML, '');
	let installedPlugin = null;
	Jetz.use({ install(jetzLibrary) { installedPlugin = jetzLibrary; } });
	assert('Jetz.use() installs a plugin', installedPlugin, Jetz);

	// gap fixes: listen() reactive callback child + ListState.asRemember()
	section('listen() and asRemember()');

	const listenCount = stateOf(0);
	const listenBox = div({ id: 'listen-box' }, 'base ', listen(parent => {
		parent.addClass(`seen-${listenCount.value}`);
		parent.text(`base ${listenCount.value}`);
	}));
	mountInto('listen', listenBox);
	assert('listen() callback runs when the parent rendered', textOf('#listen-box'), 'base 0');
	assert('listen() does not render a wrapper node', find('#listen-box').children.length, 0);
	listenCount.value = 3;
	assert('listen() callback re-runs on state change', textOf('#listen-box'), 'base 3');
	assert('listen() callback receives the parent element', find('#listen-box').classList.contains('seen-3'), true);
	let stoppedRuns = 0;
	const stoppedListener = listen(() => stoppedRuns++);
	listenBox.append(stoppedListener);
	stoppedListener.stop();
	const runsAtStop = stoppedRuns;
	listenCount.value = 4;
	assert('stop() unregisters the listener', stoppedRuns, runsAtStop);

	assert('asRemember() marks the list as remembered', lateRememberedList.isRemember, true);
	assert('asRemember() keeps the current values', JSON.stringify(lateRememberedList.values), '["seed"]');
	lateRememberedList.set(['from-phase-1']); // verified after the reload below
	lateRememberedList.push('also-pushed');

	// component lifecycle: onCreate / onMount / onUpdate / onDestroy
	section('component lifecycle');

	// class component
	const classLog = [];
	class LifecycleCard extends Component {
		render() { return div({ id: 'lifecycle-class' }, 'class card'); }
		onCreate() { classLog.push('create'); }
		onMount() { classLog.push('mount'); }
		onUpdate() { classLog.push('update'); }
		onDestroy() { classLog.push('destroy'); }
	}
	mountInto('lifecycle-class-slot', div(LifecycleCard.new()));
	assert('class onCreate runs before render, onMount after attach', classLog.join(','), 'create,mount');

	const lifecycleState = stateOf(0);
	lifecycleState.value = 1;
	assert('class onUpdate runs on state change', classLog.join(','), 'create,mount,update');

	find('#section-lifecycle-class-slot').innerHTML = ''; // simulate external removal
	lifecycleState.value = 2; // sweep runs on triggerByState
	assert('class onDestroy fires when its node is detached', classLog.join(','), 'create,mount,update,destroy');

	// function component with standalone hooks (props via closure)
	const fnLog = [];
	const lifecycleUser = { name: 'Ada' };
	function LifecycleUser() {
		onCreate(() => fnLog.push('create'));
		onMount(() => fnLog.push('mount'));
		onUpdate(() => fnLog.push('update'));
		onDestroy(() => fnLog.push('destroy'));
		return div({ id: 'lifecycle-fn' }, `user ${lifecycleUser.name}`);
	}
	mountInto('lifecycle-fn-slot', div(LifecycleUser));
	assert('function component renders', textOf('#lifecycle-fn'), 'user Ada');
	assert('function onCreate/onMount fire', fnLog.join(','), 'create,mount');

	const fnState = stateOf(0);
	fnState.value = 1;
	assert('function onUpdate fires on state change', fnLog.join(','), 'create,mount,update');

	// remove() path fires onDestroy
	const fnBox = find('#lifecycle-fn').$;
	fnBox.remove();
	fnState.value = 2;
	assert('function onDestroy fires on element.remove()', fnLog.join(','), 'create,mount,update,destroy');

	// landing page + router navigation
	section('landing page & router');

	// render the landing page directly (verifies the home-page.html conversion)
	mountInto('landing-direct-slot', Landing());
	assert('landing renders its root #landing-page', !!find('#section-landing-direct-slot #landing-page'), true);
	assert('landing hero heading is present', textOf('#section-landing-direct-slot #landing-page h1'), 'The marketplace for premium digital assets');
	assert('landing renders all 6 product cards', findAll('#section-landing-direct-slot #product-grid > div').length, 6);
	assert('landing nav has the template links', textOf('#section-landing-direct-slot nav #navbar-sticky ul'), 'DiscoverCategoriesMy Assets');
	assert('landing footer has social links', findAll('#section-landing-direct-slot footer a').length >= 3, true);

	// search filtering (the module-level `products` list is the grid's source of truth)
	const searchInput = find('#section-landing-direct-slot #default-search');
	searchInput.value = 'React';
	searchInput.dispatchEvent(new Event('input', { bubbles: true }));
	assert('search filters the product grid', findAll('#section-landing-direct-slot #product-grid > div').length, 1);
	assert('search keeps only the matching card', textOf('#section-landing-direct-slot #product-grid h3'), 'Advanced React Patterns');
	searchInput.value = '';
	searchInput.dispatchEvent(new Event('input', { bubbles: true }));
	assert('clearing the search restores every card', findAll('#section-landing-direct-slot #product-grid > div').length, 6);

	// wire the full router + nav into a mount target so link() clicks navigate
	const router = new Router(
		route('/', Landing),
		route('landing', Landing),
		route('counter', counterPage),
		route('open-todo', counterPage) // reuse the counter page as a stand-in for the todo component
	);
	Jetz.use(router);
	mountInto('router-slot', main(Jetz.$route.browser()));

	// navigate programmatically
	router.to('/landing');
	assert('router.to() renders the landing route', !!find('#section-router-slot #landing-page'), true);
	assert('router keeps the hero heading after navigation', textOf('#section-router-slot #landing-page h1'), 'The marketplace for premium digital assets');
	router.to('counter');
	const counterEl1 = find('#section-router-slot #text-counter');
	assert('router.to() renders the counter route', counterEl1 ? counterEl1.textContent.slice(0, 7) : 'NOT FOUND', 'Count :');

	// a link() click must navigate too (the nav "My Assets" link uses link())
	router.to('/');
	const counterLink = Array.from(findAll('#section-router-slot nav a')).find(a => a.textContent === 'My Assets');
	assert('link() anchor exists', !!counterLink, true);
	counterLink.click();
	const counterEl2 = find('#section-router-slot #text-counter');
	assert('link() click renders the counter route', counterEl2 ? counterEl2.textContent.slice(0, 7) : 'NOT FOUND', 'Count :');
	// back to landing
	router.to('/landing');
	assert('router navigates back to landing', !!find('#section-router-slot #landing-page'), true);
	// leave the URL at "/" so the rememberOf reload phase runs on the same pathname it persisted under
	router.to('/');

	// addScript

	const loadExternal = new Promise(resolve => {
		const timer = setTimeout(() => resolve('timeout'), 5000);
		addScript('external.js', {
			async: true,
			onload() {
				clearTimeout(timer);
				resolve('loaded');
			}
		});
	});

	loadExternal.then(status => {
		const scriptTag = document.querySelector('script[src="external.js"]');
		assert('addScript() loads the script file', status, 'loaded');
		assert('addScript() runs the loaded script', window.__JETZ_SMOKE_SCRIPT__, 'loaded');
		assert('addScript() forwards element attributes', scriptTag.getAttribute('async'), 'true');
		assert('addScript() appends the script to the body', scriptTag.parentElement.tagName, 'BODY');

		// phase 1 done: persist the results and ask the runner for one reload,
		// the reload phase verifies rememberOf
		rememberedNumber.value = 42;
		rememberedList.push('persisted');
		keyedRememberedList.push('keyed-persisted');
		sessionStorage.setItem(KEY_RESULTS, results.join('\n'));
		window.__SMOKE_RELOAD__ = true;
		finish();
	});
}

// ---------------------------------------------------------------------------
// dispatch: phase 1 runs the suite, the second page load only checks rememberOf
// ---------------------------------------------------------------------------
function reportCrash(error) {
	results.push(`FAIL :: ${currentSection} :: suite crashed | ${error && error.stack ? error.stack.split('\n').slice(0, 4).join(' | ') : error}`);
	finish();
}

try {
	if (isReloadPhase) {
		runReloadPhase();
	} else {
		runMainSuite();
	}
} catch (error) {
	reportCrash(error);
}
